version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
#    command:
#      - python
#      - manage.py
#      - runserver
#      - 0.0.0.0:8000
    command: >
      bash -c "python manage.py migrate &&
               python manage.py loaddata fixtures/products-fixtures.json &&
               python manage.py loaddata fixtures/users-fixtures.json 
               python manage.py loaddata fixtures/userprofile-fixtures.json 
               python manage.py loaddata fixtures/orders-fixtures.json  
               python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    volumes:
      - .shop_megano/megano/database:/app/database
