# Generated by Django 4.2 on 2024-06-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('usercart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='products',
            field=models.ManyToManyField(related_name='products', through='usercart.BasketItem', to='product.product'),
        ),
    ]
