# Generated by Django 4.2 on 2024-06-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
