# Generated by Django 4.2 on 2024-06-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_page_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='page_number',
        ),
        migrations.AddField(
            model_name='product',
            name='show_on_page',
            field=models.BooleanField(default=False),
        ),
    ]
