# Generated by Django 4.2 on 2024-06-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale',
            new_name='sale_status',
        ),
    ]
