# Generated by Django 4.2 on 2024-06-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_page_number_product_show_on_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='show_on_page',
        ),
        migrations.AddField(
            model_name='product',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
