# Generated by Django 4.2 on 2024-06-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_show_on_page_product_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
