# Generated by Django 4.2 on 2024-06-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_last_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_page',
        ),
    ]
