# Generated by Django 4.2 on 2024-06-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_fulldescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='page_number',
        ),
    ]
