# Generated by Django 4.2 on 2024-06-03 14:48

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_page_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to=product.models.category_image_directory_path)),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='product.categoryproduct')),
            ],
            options={
                'verbose_name': 'Category image',
                'verbose_name_plural': 'Category images',
                'ordering': ['pk'],
            },
        ),
    ]
