# Generated by Django 4.2 on 2024-06-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productspecification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.TextField(blank=True),
        ),
    ]
