# Generated by Django 4.2 on 2024-06-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersdeliverytype',
            name='deliveryType',
            field=models.CharField(default='ordinary', max_length=100),
        ),
    ]
