# Generated by Django 4.2 on 2024-06-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderscountproducts_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalCost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
